### ISSUE TITLE
Implement flexbox for layout

### ISSUE THREAD

**Issue by jrmykolyn** [jrmykolyn/llc-css-fundamentals#1]
**TODO**
- [X] Update `final.css` file to use `flex` instead of `float`.
- [X] Removed old/unused CSS declarations and rules (ie. `overflow: hidden;`).
- [X] Update all 'example' CSS files (ie. ensure that all supporting CSS is consistent with new material).
  - NOTE: This issue is *not* concerned with the `extras-*` example files, which don't appear to be used or referenced anywhere within the workshop material.
- [X] Update `float`-related slides.

**Comment by jrmykolyn** [comment]
This update is complete and has been merged into the `content-development` branch.
